
 name: CI

 on:
   schedule:
     - cron: "* * * * *"
   push:
     branches: [ master ]
   pull_request:
     branches: [ master ]
 jobs:
   update-data:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v2
     - name: Downloading new data/data.json file
       env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
       run: |
          chmod +x ./updater/main.py
          ./updater/main.py "$API_TOKEN"
     - name: Updating data/data.json
       uses: test-room-7/action-update-file@v1.5.0
       with:
         file-path: data/data.json
         commit-msg: Atualizando data/data.json
         github-token: ${{ secrets.GITHUB_TOKEN }}
